/** 弹层定位：Bot 对话策略表单分组。 */

/** 后端未返回 label 时的字段标题兜底（与 Pallas-Bot field_labels.py 对齐）。 */
export const FALLBACK_FIELD_LABELS: Record<string, string> = {
  llm_chat_enabled: "启用智能对话",
  chat_enable: "启用酒后 RWKV（独立通道）",
  llm_session_enabled: "记住多轮上下文",
  llm_session_user_window: "用户上下文条数",
  llm_session_group_window: "群旁听上下文条数",
  llm_session_group_ambient_enabled: "注入群旁听上下文",
  llm_session_user_ttl_sec: "用户会话过期（秒）",
  llm_session_private_ttl_sec: "私聊会话过期（秒）",
  llm_session_max_content_len: "单条会话字数上限",
  llm_session_strip_vision_enabled: "写入会话时去掉图片",
  llm_session_summary_enabled: "会话过长时生成摘要",
  llm_session_summary_threshold: "触发摘要的消息条数",
  llm_session_summary_keep_messages: "摘要后保留近期条数",
  llm_speak_perception_enabled: "启用发言感知",
  llm_speak_mention_enabled: "别名提及时进对话",
  llm_speak_ambient_enabled: "氛围插嘴",
  llm_speak_ambient_rate: "氛围插嘴概率",
  llm_speak_ambient_min_score: "氛围插嘴最低分",
  llm_speak_ambient_cooldown_sec: "氛围插嘴冷却（秒）",
  llm_speak_min_alias_len: "别名最短匹配长度",
  llm_speak_followup_enabled: "硬触发后续聊软窗",
  llm_speak_followup_window_sec: "续聊软窗时长（秒）",
  llm_speak_followup_max_total_sec: "续聊最长总时长（秒）",
  llm_chat_char_budget: "LLM 对话上下文字符预算",
  llm_tools_enabled: "允许调用工具",
  llm_tools_selective: "按意图筛选工具",
  llm_tools_soft_recall_enabled: "软召回工具候选",
  llm_tools_soft_recall_min_score: "软召回最低匹配分",
  llm_tools_soft_recall_max_candidates: "软召回最多候选数",
  llm_tools_max_rounds: "工具调用最多轮数",
  llm_tools_blacklist: "工具黑名单",
  llm_tools_desc_max_len: "工具描述最大长度",
  mcp_servers: "MCP 服务器",
  llm_mcp_http_allowlist: "MCP HTTP 允许前缀",
  web_search_api_url: "搜索接口完整地址",
  tavily_api_key: "搜索接口密钥",
  llm_governance_enabled: "限制 LLM 对话频率与字数",
  conversation_feature_level: "对话能力档位",
  llm_repeater_feedback_enabled: "收集 LLM 对话纠错",
  llm_repeater_bias_enabled: "纠错参与接话打分",
  llm_memory_rag_enabled: "群记忆检索",
  llm_vector_retrieve: "记忆/知识检索模式",
  llm_embedding_model: "Embedding 模型",
  llm_embedding_provider: "向量提供方",
  llm_embedding_provider_id: "Embedding 线路",
  llm_embedding_base_url: "Embedding 接口地址",
  llm_embedding_api_key: "Embedding API Key",
  llm_embedding_api_backends: "Embedding 备线",
  llm_memory_rag_top_k: "记忆检索条数",
  llm_memory_max_per_group: "每群记忆上限",
  llm_memory_content_max_len: "单条记忆字数上限",
  llm_memory_auto_episode_enabled: "自动沉淀会话为记忆",
  llm_memory_auto_episode_cooldown_sec: "自动沉淀冷却（秒）",
  llm_memory_auto_episode_daily_budget: "自动摘要每日预算",
  llm_memory_auto_ip_enabled: "自动提炼 IP 知识",
  llm_memory_auto_ip_daily_budget: "IP 知识每日预算",
  llm_memory_auto_ip_cooldown_sec: "IP 知识提炼冷却（秒）",
  llm_memory_graph_extract_enabled: "记忆图谱抽取",
  llm_memory_graph_extract_on_write: "写入后自动抽取图谱",
  llm_memory_hiergraph_max_layers: "分层图谱最大层数",
  llm_relationship_notes_enabled: "关系备注",
  llm_output_filter_enabled: "回复输出过滤",
  llm_output_filter_chat_hard_phrases: "LLM 对话硬拦截词",
  llm_output_filter_chat_soft_phrases: "LLM 对话软拦截词",
  llm_chat_max_concurrency: "LLM 对话并发上限",
  llm_reply_gate_enabled: "过滤无意义 @",
  llm_current_turn_decision_enabled: "启用本轮动作决策",
  llm_chat_queue_merge: "冷却期合并多条 @",
  llm_reply_postprocess_enabled: "回复后处理",
  llm_reply_typo_enabled: "偶发近音错别字",
  llm_reply_typo_rate: "单字错别字概率",
  llm_reply_split_enabled: "按句拆成多条",
  llm_reply_split_max_chars: "拆条单段字数上限",
  llm_sticker_fit_enabled: "表情适配与反馈",
  llm_reply_effect_eval_enabled: "记录回复效果评分",
  llm_persona_output_firewall: "人设输出防火墙",
};

export type LlmBotFieldGroupTier = "essential" | "advanced";

export interface LlmBotFieldGroupDef {
  title: string;
  keys: readonly string[];
  tier: LlmBotFieldGroupTier;
  hint?: string;
  anchorId?: string;
}

/** 策略表单：会话/记忆细项已拆到对话子面板，此处只留总开关级入口。 */
export const LLM_BOT_FIELD_GROUPS: ReadonlyArray<LlmBotFieldGroupDef> = [
  {
    title: "功能开关",
    tier: "essential",
    keys: [
      "llm_chat_enabled",
      "llm_tools_enabled",
    ],
    hint: "先开「智能对话」。本轮动作决策默认关：关着不额外花钱；若开启，模型在「接入 → 任务编排」里配。",
  },
  {
    title: "发言感知",
    tier: "essential",
    anchorId: "llm-speak-perception",
    keys: [
      "llm_speak_perception_enabled",
      "llm_speak_mention_enabled",
      "llm_speak_ambient_enabled",
      "llm_speak_followup_enabled",
    ],
    hint: "未 @ 时是否因「牛牛」等别名或氛围进智能对话；细调见进阶分组。",
  },
  {
    title: "联网搜索",
    tier: "essential",
    anchorId: "llm-web-search",
    keys: ["web_search_api_url", "tavily_api_key"],
    hint: "群友说「搜一下」时用。地址和密钥都填、并开启「允许调用工具」才会真联网；填法点字段旁「？」。",
  },
  {
    title: "学习闭环",
    tier: "essential",
    anchorId: "learning-loop",
    keys: [
      "llm_repeater_feedback_enabled",
      "llm_repeater_bias_enabled",
    ],
    hint: "把成功发出的智能对话短句，用于之后的接话选句纠错。坏样本先在会话页排除。",
  },
  {
    title: "记忆与知识",
    tier: "essential",
    anchorId: "llm-memory-knowledge",
    keys: [
      "llm_memory_auto_episode_summary_enabled",
      "llm_memory_auto_episode_daily_budget",
      "llm_memory_auto_ip_enabled",
      "llm_memory_auto_ip_daily_budget",
      "llm_knowledge_file_ingest_enabled",
    ],
    hint: "让牛牛记住群里的共同事件（自动摘要）和聊到的作品设定（IP 知识）。两者都会额外调用一次模型，预算项用于控制每日费用。",
  },
  {
    title: "策略细调",
    tier: "advanced",
    keys: [
      "chat_enable", "chat_tts_enable", "drunk_tts_min_chars", "drunk_tts_min_drunkenness",
      "llm_governance_enabled", "conversation_feature_level",
      "llm_current_turn_decision_enabled", "llm_tools_selective", "llm_tools_soft_recall_enabled",
      "llm_tools_soft_recall_min_score", "llm_tools_soft_recall_max_candidates", "llm_tools_max_rounds",
      "llm_tools_blacklist", "llm_tools_desc_max_len",
    ],
    hint: "默认无需调整；用于兼容旧通道、工具筛选与维护者策略调优。",
  },
  {
    title: "发言感知细调",
    tier: "advanced",
    anchorId: "llm-speak-perception-tuning",
    keys: [
      "llm_speak_ambient_rate",
      "llm_speak_ambient_min_score",
      "llm_speak_ambient_cooldown_sec",
      "llm_speak_ambient_budget_limit",
      "llm_speak_ambient_budget_window_sec",
      "llm_speak_min_alias_len",
      "llm_speak_followup_window_sec",
      "llm_speak_followup_max_total_sec",
    ],
    hint: "氛围插嘴概率/冷却与续聊软窗时长。",
  },
  {
    title: "输出过滤",
    tier: "advanced",
    keys: [
      "llm_output_filter_enabled",
      "llm_output_filter_chat_hard_phrases",
      "llm_output_filter_chat_soft_phrases",
      "llm_persona_output_firewall",
    ],
    hint: "拦住客服腔、乱邀约等怪句；人设防火墙另拦泄提示词、舞台旁白、自称模型。硬拦=直接挡；接话被拦时优先退回语料原文。",
  },
  {
    title: "对话排队",
    tier: "advanced",
    keys: [
      "llm_chat_queue_enabled",
      "llm_chat_queue_max",
      "llm_chat_queue_wait_sec",
      "llm_chat_queue_merge",
    ],
    hint: "高峰并发占满时，显式 @ 对话排队等待的策略：是否排队、最多排几个、等多久；冷却期连发多条 @ 是否合并成一次回复。",
  },
  {
    title: "并发与限流",
    tier: "advanced",
    keys: [
      "llm_chat_max_concurrency",
      "llm_reply_gate_enabled",
    ],
    hint: "控制 LLM 对话并发，以及无意义 @ 是否直接忽略。默认偏保守，活跃群可再调严省额度。",
  },
  {
    title: "表情图",
    tier: "advanced",
    anchorId: "llm-sticker",
    keys: [
      "llm_chat_sticker_enabled",
      "llm_chat_sticker_cooldown_sec",
      "llm_sticker_vision_enabled",
      "llm_sticker_vision_candidate_count",
      "llm_sticker_vision_timeout_sec",
      "llm_sticker_vision_max_per_hour",
    ],
    hint: "Bot 文本按需附带 Repeater 表情图；视觉模型可进一步从语义候选中挑更贴的图，候选越多越准但更耗视觉模型额度。",
  },
  {
    title: "表达学习",
    tier: "advanced",
    keys: [
      "llm_expression_inject_enabled",
      "llm_expression_learn_enabled",
      "llm_expression_auto_promote_enabled",
      "llm_expression_retrieve_limit",
    ],
    hint: "让牛牛从群聊里学习群体表达习惯（黑话、口癖）并在回复中自然使用；自动晋升会把高频表达提升为常用偏好。",
  },
  {
    title: "回复后处理",
    tier: "advanced",
    keys: [
      "llm_reply_postprocess_enabled",
      "llm_reply_typo_enabled",
      "llm_reply_typo_rate",
      "llm_reply_split_enabled",
      "llm_reply_split_max_chars",
      "llm_sticker_fit_enabled",
      "llm_reply_effect_eval_enabled",
    ],
    hint: "发出前的可选花样：偶发错别字、拆成多条气泡、表情适配与效果记分。须先开总开关；结果不写回语料学习。",
  },
];

export const LLM_SESSION_DETAIL_KEYS = [
  "llm_session_user_window",
  "llm_session_group_window",
  "llm_session_group_ambient_enabled",
  "llm_session_user_ttl_sec",
  "llm_session_private_ttl_sec",
  "llm_session_max_content_len",
  "llm_session_strip_vision_enabled",
  "llm_session_summary_enabled",
  "llm_session_summary_threshold",
  "llm_session_summary_keep_messages",
] as const;

export const LLM_MEMORY_DETAIL_KEYS = [
  "llm_vector_retrieve",
  "llm_embedding_provider",
  "llm_embedding_provider_id",
  "llm_embedding_model",
  "llm_embedding_base_url",
  "llm_embedding_api_key",
  "llm_embedding_api_backends",
  "llm_memory_rag_top_k",
  "llm_memory_max_per_group",
  "llm_memory_content_max_len",
  "llm_memory_auto_episode_enabled",
  "llm_memory_auto_episode_cooldown_sec",
  "llm_memory_graph_extract_enabled",
  "llm_memory_graph_extract_on_write",
  "llm_memory_hiergraph_max_layers",
  "llm_relationship_notes_enabled",
] as const;

export const LLM_BUDGET_DETAIL_KEYS = ["llm_chat_char_budget"] as const;

/** 媒体地址已迁到「媒体」分段；会话/记忆/预算细项在专面，策略表单隐藏避免重复。 */
export const HIDDEN_LLM_STRATEGY_FIELDS = new Set([
  "ai_server_host",
  "ai_server_port",
  "llm_base_url",
  "llm_api_key",
  "llm_model",
  "llm_session_enabled",
  "llm_session_user_window",
  "llm_session_group_window",
  "llm_session_group_ambient_enabled",
  "llm_session_user_ttl_sec",
  "llm_session_private_ttl_sec",
  "llm_session_max_content_len",
  "llm_session_strip_vision_enabled",
  "llm_session_summary_enabled",
  "llm_session_summary_threshold",
  "llm_session_summary_keep_messages",
  "llm_chat_char_budget",
  "llm_memory_rag_enabled",
  "llm_vector_retrieve",
  "llm_embedding_provider",
  "llm_embedding_provider_id",
  "llm_embedding_model",
  "llm_embedding_base_url",
  "llm_embedding_api_key",
  "llm_embedding_api_backends",
  "llm_memory_rag_top_k",
  "llm_memory_max_per_group",
  "llm_memory_content_max_len",
  "llm_memory_auto_episode_enabled",
  "llm_memory_auto_episode_cooldown_sec",
  "llm_memory_auto_ip_cooldown_sec",
  "llm_session_user_storage_window",
  "llm_session_summary_cooldown_sec",
  "llm_sticker_label_backfill_enabled",
  "llm_sticker_label_backfill_daily_limit",
  "llm_sticker_label_realtime_daily_limit",
  "llm_memory_graph_extract_enabled",
  "llm_memory_graph_extract_on_write",
  "llm_memory_hiergraph_max_layers",
  "llm_relationship_notes_enabled",
  "mcp_servers",
  "llm_mcp_http_allowlist",
]);

export function llmBotFieldGroupsForMode(isSimpleMode: boolean): ReadonlyArray<LlmBotFieldGroupDef> {
  if (!isSimpleMode) return LLM_BOT_FIELD_GROUPS;
  return LLM_BOT_FIELD_GROUPS.filter((group) => group.tier === "essential");
}
